### ISSUE TITLE
commit clobbered README

### ISSUE THREAD

**Issue by gtalusan** [AT0myks/reolink-fw-archive#45]
Looks like this auto update clobbered the very useful README: https://github.com/AT0myks/reolink-fw-archive/commit/e45fb4db0d0123e028241f2e3b74bd952f8081a5

**Comment by SvenJ76** [comment]
no updates here?

**Comment by nowherenearaninja** [comment]
OUCH!
Keeping that one was very appreciated and my main purpose of visiting this site.
Fingers crossed you find a way to get it back without too much hazzle.
If only there were a system that kept track of revisions...

**Comment by gtalusan** [comment]
FYI PR to workaround the issue at #50 - you may check my [fork](https://github.com/gtalusan/reolink-fw-archive) to see the README.

**Comment by AT0myks** [comment]
@gtalusan Thanks a lot for keeping the project alive. After this was fixed, I saw your fork and used it to recreate all the auto update commits from April 12 to November 15 so that the history in the main repo can be as accurate as possible. Even then, I'd still like to provide some feedback for your PR.
